// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.19.4
// source: order.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Cursor        int64                  `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Ps            int32                  `protobuf:"varint,4,opt,name=ps,proto3" json:"ps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrdersRequest) Reset() {
	*x = OrdersRequest{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdersRequest) ProtoMessage() {}

func (x *OrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdersRequest.ProtoReflect.Descriptor instead.
func (*OrdersRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrdersRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrdersRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrdersRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *OrdersRequest) GetPs() int32 {
	if x != nil {
		return x.Ps
	}
	return 0
}

type OrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Orderitem           `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	IsEnd         bool                   `protobuf:"varint,2,opt,name=is_end,json=isEnd,proto3" json:"is_end,omitempty"`
	CreateTime    string                 `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrdersResponse) Reset() {
	*x = OrdersResponse{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdersResponse) ProtoMessage() {}

func (x *OrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdersResponse.ProtoReflect.Descriptor instead.
func (*OrdersResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrdersResponse) GetOrders() []*Orderitem {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *OrdersResponse) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

func (x *OrdersResponse) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type Orderitem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Orderid          string                 `protobuf:"bytes,2,opt,name=orderid,proto3" json:"orderid,omitempty"`
	Userid           int64                  `protobuf:"varint,3,opt,name=userid,proto3" json:"userid,omitempty"`
	Proid            int64                  `protobuf:"varint,4,opt,name=proid,proto3" json:"proid,omitempty"`
	Proname          string                 `protobuf:"bytes,5,opt,name=proname,proto3" json:"proname,omitempty"`
	Proimage         string                 `protobuf:"bytes,6,opt,name=proimage,proto3" json:"proimage,omitempty"`
	Currentunitprice float64                `protobuf:"fixed64,7,opt,name=currentunitprice,proto3" json:"currentunitprice,omitempty"`
	Quantity         int64                  `protobuf:"varint,8,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Totalprice       float64                `protobuf:"fixed64,9,opt,name=totalprice,proto3" json:"totalprice,omitempty"`
	CreateTime       int64                  `protobuf:"varint,10,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime       int64                  `protobuf:"varint,11,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Orderitem) Reset() {
	*x = Orderitem{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Orderitem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Orderitem) ProtoMessage() {}

func (x *Orderitem) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Orderitem.ProtoReflect.Descriptor instead.
func (*Orderitem) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *Orderitem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Orderitem) GetOrderid() string {
	if x != nil {
		return x.Orderid
	}
	return ""
}

func (x *Orderitem) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *Orderitem) GetProid() int64 {
	if x != nil {
		return x.Proid
	}
	return 0
}

func (x *Orderitem) GetProname() string {
	if x != nil {
		return x.Proname
	}
	return ""
}

func (x *Orderitem) GetProimage() string {
	if x != nil {
		return x.Proimage
	}
	return ""
}

func (x *Orderitem) GetCurrentunitprice() float64 {
	if x != nil {
		return x.Currentunitprice
	}
	return 0
}

func (x *Orderitem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Orderitem) GetTotalprice() float64 {
	if x != nil {
		return x.Totalprice
	}
	return 0
}

func (x *Orderitem) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Orderitem) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Pid           int64                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CreateOrderRequest) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

type Orders struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Userid        int64                  `protobuf:"varint,2,opt,name=userid,proto3" json:"userid,omitempty"`
	Shoppingid    int64                  `protobuf:"varint,3,opt,name=shoppingid,proto3" json:"shoppingid,omitempty"`
	Payment       float64                `protobuf:"fixed64,4,opt,name=payment,proto3" json:"payment,omitempty"`
	Paymenttype   int64                  `protobuf:"varint,5,opt,name=paymenttype,proto3" json:"paymenttype,omitempty"`
	Postage       int64                  `protobuf:"varint,6,opt,name=postage,proto3" json:"postage,omitempty"`
	Status        int64                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime    int64                  `protobuf:"varint,8,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,9,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Orders) Reset() {
	*x = Orders{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Orders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Orders) ProtoMessage() {}

func (x *Orders) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Orders.ProtoReflect.Descriptor instead.
func (*Orders) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *Orders) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Orders) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *Orders) GetShoppingid() int64 {
	if x != nil {
		return x.Shoppingid
	}
	return 0
}

func (x *Orders) GetPayment() float64 {
	if x != nil {
		return x.Payment
	}
	return 0
}

func (x *Orders) GetPaymenttype() int64 {
	if x != nil {
		return x.Paymenttype
	}
	return 0
}

func (x *Orders) GetPostage() int64 {
	if x != nil {
		return x.Postage
	}
	return 0
}

func (x *Orders) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Orders) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Orders) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type AddOrderReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Userid           int64                  `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Productid        int64                  `protobuf:"varint,2,opt,name=productid,proto3" json:"productid,omitempty"`
	Quantity         int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Postage          int64                  `protobuf:"varint,4,opt,name=postage,proto3" json:"postage,omitempty"`
	ReceiveAddressId int64                  `protobuf:"varint,5,opt,name=receiveAddressId,proto3" json:"receiveAddressId,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AddOrderReq) Reset() {
	*x = AddOrderReq{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderReq) ProtoMessage() {}

func (x *AddOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderReq.ProtoReflect.Descriptor instead.
func (*AddOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *AddOrderReq) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *AddOrderReq) GetProductid() int64 {
	if x != nil {
		return x.Productid
	}
	return 0
}

func (x *AddOrderReq) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AddOrderReq) GetPostage() int64 {
	if x != nil {
		return x.Postage
	}
	return 0
}

func (x *AddOrderReq) GetReceiveAddressId() int64 {
	if x != nil {
		return x.ReceiveAddressId
	}
	return 0
}

type AddOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrderResp) Reset() {
	*x = AddOrderResp{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderResp) ProtoMessage() {}

func (x *AddOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderResp.ProtoReflect.Descriptor instead.
func (*AddOrderResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *AddOrderResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOrderByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIdReq) Reset() {
	*x = GetOrderByIdReq{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIdReq) ProtoMessage() {}

func (x *GetOrderByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIdReq.ProtoReflect.Descriptor instead.
func (*GetOrderByIdReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *GetOrderByIdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetOrderByIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Orders                `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"` //order
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIdResp) Reset() {
	*x = GetOrderByIdResp{}
	mi := &file_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIdResp) ProtoMessage() {}

func (x *GetOrderByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIdResp.ProtoReflect.Descriptor instead.
func (*GetOrderByIdResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{9}
}

func (x *GetOrderByIdResp) GetOrder() *Orders {
	if x != nil {
		return x.Order
	}
	return nil
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x05order\"h\n" +
	"\rOrdersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\x03R\x06cursor\x12\x0e\n" +
	"\x02ps\x18\x04 \x01(\x05R\x02ps\"r\n" +
	"\x0eOrdersResponse\x12(\n" +
	"\x06orders\x18\x01 \x03(\v2\x10.order.OrderitemR\x06orders\x12\x15\n" +
	"\x06is_end\x18\x02 \x01(\bR\x05isEnd\x12\x1f\n" +
	"\vcreate_time\x18\x03 \x01(\tR\n" +
	"createTime\"\xc1\x02\n" +
	"\tOrderitem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\aorderid\x18\x02 \x01(\tR\aorderid\x12\x16\n" +
	"\x06userid\x18\x03 \x01(\x03R\x06userid\x12\x14\n" +
	"\x05proid\x18\x04 \x01(\x03R\x05proid\x12\x18\n" +
	"\aproname\x18\x05 \x01(\tR\aproname\x12\x1a\n" +
	"\bproimage\x18\x06 \x01(\tR\bproimage\x12*\n" +
	"\x10currentunitprice\x18\a \x01(\x01R\x10currentunitprice\x12\x1a\n" +
	"\bquantity\x18\b \x01(\x03R\bquantity\x12\x1e\n" +
	"\n" +
	"totalprice\x18\t \x01(\x01R\n" +
	"totalprice\x12\x1e\n" +
	"\n" +
	"createTime\x18\n" +
	" \x01(\x03R\n" +
	"createTime\x12\x1e\n" +
	"\n" +
	"updateTime\x18\v \x01(\x03R\n" +
	"updateTime\"8\n" +
	"\x12CreateOrderRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x03R\x03pid\"\x15\n" +
	"\x13CreateOrderResponse\"\xfe\x01\n" +
	"\x06Orders\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06userid\x18\x02 \x01(\x03R\x06userid\x12\x1e\n" +
	"\n" +
	"shoppingid\x18\x03 \x01(\x03R\n" +
	"shoppingid\x12\x18\n" +
	"\apayment\x18\x04 \x01(\x01R\apayment\x12 \n" +
	"\vpaymenttype\x18\x05 \x01(\x03R\vpaymenttype\x12\x18\n" +
	"\apostage\x18\x06 \x01(\x03R\apostage\x12\x16\n" +
	"\x06status\x18\a \x01(\x03R\x06status\x12\x1e\n" +
	"\n" +
	"createTime\x18\b \x01(\x03R\n" +
	"createTime\x12\x1e\n" +
	"\n" +
	"updateTime\x18\t \x01(\x03R\n" +
	"updateTime\"\xa5\x01\n" +
	"\vAddOrderReq\x12\x16\n" +
	"\x06userid\x18\x01 \x01(\x03R\x06userid\x12\x1c\n" +
	"\tproductid\x18\x02 \x01(\x03R\tproductid\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\x12\x18\n" +
	"\apostage\x18\x04 \x01(\x03R\apostage\x12*\n" +
	"\x10receiveAddressId\x18\x05 \x01(\x03R\x10receiveAddressId\"\x1e\n" +
	"\fAddOrderResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"!\n" +
	"\x0fGetOrderByIdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"7\n" +
	"\x10GetOrderByIdResp\x12#\n" +
	"\x05order\x18\x01 \x01(\v2\r.order.OrdersR\x05order2\xd4\x03\n" +
	"\x05Order\x125\n" +
	"\x06Orders\x12\x14.order.OrdersRequest\x1a\x15.order.OrdersResponse\x12D\n" +
	"\vCreateOrder\x12\x19.order.CreateOrderRequest\x1a\x1a.order.CreateOrderResponse\x12I\n" +
	"\x10CreateOrderCheck\x12\x19.order.CreateOrderRequest\x1a\x1a.order.CreateOrderResponse\x12F\n" +
	"\rRollbackOrder\x12\x19.order.CreateOrderRequest\x1a\x1a.order.CreateOrderResponse\x129\n" +
	"\x0eCreateOrderDTM\x12\x12.order.AddOrderReq\x1a\x13.order.AddOrderResp\x12?\n" +
	"\x14CreateOrderDTMRevert\x12\x12.order.AddOrderReq\x1a\x13.order.AddOrderResp\x12?\n" +
	"\fGetOrderById\x12\x16.order.GetOrderByIdReq\x1a\x17.order.GetOrderByIdRespB\tZ\a./orderb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_order_proto_goTypes = []any{
	(*OrdersRequest)(nil),       // 0: order.OrdersRequest
	(*OrdersResponse)(nil),      // 1: order.OrdersResponse
	(*Orderitem)(nil),           // 2: order.Orderitem
	(*CreateOrderRequest)(nil),  // 3: order.CreateOrderRequest
	(*CreateOrderResponse)(nil), // 4: order.CreateOrderResponse
	(*Orders)(nil),              // 5: order.Orders
	(*AddOrderReq)(nil),         // 6: order.AddOrderReq
	(*AddOrderResp)(nil),        // 7: order.AddOrderResp
	(*GetOrderByIdReq)(nil),     // 8: order.GetOrderByIdReq
	(*GetOrderByIdResp)(nil),    // 9: order.GetOrderByIdResp
}
var file_order_proto_depIdxs = []int32{
	2, // 0: order.OrdersResponse.orders:type_name -> order.Orderitem
	5, // 1: order.GetOrderByIdResp.order:type_name -> order.Orders
	0, // 2: order.Order.Orders:input_type -> order.OrdersRequest
	3, // 3: order.Order.CreateOrder:input_type -> order.CreateOrderRequest
	3, // 4: order.Order.CreateOrderCheck:input_type -> order.CreateOrderRequest
	3, // 5: order.Order.RollbackOrder:input_type -> order.CreateOrderRequest
	6, // 6: order.Order.CreateOrderDTM:input_type -> order.AddOrderReq
	6, // 7: order.Order.CreateOrderDTMRevert:input_type -> order.AddOrderReq
	8, // 8: order.Order.GetOrderById:input_type -> order.GetOrderByIdReq
	1, // 9: order.Order.Orders:output_type -> order.OrdersResponse
	4, // 10: order.Order.CreateOrder:output_type -> order.CreateOrderResponse
	4, // 11: order.Order.CreateOrderCheck:output_type -> order.CreateOrderResponse
	4, // 12: order.Order.RollbackOrder:output_type -> order.CreateOrderResponse
	7, // 13: order.Order.CreateOrderDTM:output_type -> order.AddOrderResp
	7, // 14: order.Order.CreateOrderDTMRevert:output_type -> order.AddOrderResp
	9, // 15: order.Order.GetOrderById:output_type -> order.GetOrderByIdResp
	9, // [9:16] is the sub-list for method output_type
	2, // [2:9] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
