// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	shippingFieldNames          = builder.RawFieldNames(&Shipping{})
	shippingRows                = strings.Join(shippingFieldNames, ",")
	shippingRowsExpectAutoSet   = strings.Join(stringx.Remove(shippingFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	shippingRowsWithPlaceHolder = strings.Join(stringx.Remove(shippingFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	shippingModel interface {
		Insert(ctx context.Context, data *Shipping) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Shipping, error)
		Update(ctx context.Context, data *Shipping) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultShippingModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Shipping struct {
		Id               uint64    `db:"id"`                // 收货信息表id
		Orderid          string    `db:"orderid"`           // 订单id
		Userid           uint64    `db:"userid"`            // 用户id
		ReceiverName     string    `db:"receiver_name"`     // 收货姓名
		ReceiverPhone    string    `db:"receiver_phone"`    // 收货固定电话
		ReceiverMobile   string    `db:"receiver_mobile"`   // 收货移动电话
		ReceiverProvince string    `db:"receiver_province"` // 省份
		ReceiverCity     string    `db:"receiver_city"`     // 城市
		ReceiverDistrict string    `db:"receiver_district"` // 区/县
		ReceiverAddress  string    `db:"receiver_address"`  // 详细地址
		CreateTime       time.Time `db:"create_time"`       // 创建时间
		UpdateTime       time.Time `db:"update_time"`       // 更新时间
	}
)

func newShippingModel(conn sqlx.SqlConn) *defaultShippingModel {
	return &defaultShippingModel{
		conn:  conn,
		table: "`shipping`",
	}
}

func (m *defaultShippingModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultShippingModel) FindOne(ctx context.Context, id uint64) (*Shipping, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", shippingRows, m.table)
	var resp Shipping
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShippingModel) Insert(ctx context.Context, data *Shipping) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, shippingRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Orderid, data.Userid, data.ReceiverName, data.ReceiverPhone, data.ReceiverMobile, data.ReceiverProvince, data.ReceiverCity, data.ReceiverDistrict, data.ReceiverAddress)
	return ret, err
}

func (m *defaultShippingModel) Update(ctx context.Context, data *Shipping) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, shippingRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Orderid, data.Userid, data.ReceiverName, data.ReceiverPhone, data.ReceiverMobile, data.ReceiverProvince, data.ReceiverCity, data.ReceiverDistrict, data.ReceiverAddress, data.Id)
	return err
}

func (m *defaultShippingModel) tableName() string {
	return m.table
}
